# Display hardware constants - matches ST7789 1.54" 240x240
DISPLAY_WIDTH = 240
DISPLAY_HEIGHT = 240
BYTES_PER_PIXEL = 2  # RGB565
FULL_FRAME_BYTES = DISPLAY_WIDTH * DISPLAY_HEIGHT * BYTES_PER_PIXEL

# Default SPI clock estimate: 40MHz typical for ST7789 on ESP32-S3
DEFAULT_SPI_CLOCK_HZ = 40_000_000
SPI_BYTES_PER_SECOND = DEFAULT_SPI_CLOCK_HZ // 8

# Timing defaults
DEFAULT_TARGET_FPS = 30
DEFAULT_FRAME_TIME_MS = 1000 // DEFAULT_TARGET_FPS

# Eye layout defaults
DEFAULT_EYE_SEPARATION = 60
DEFAULT_EYE_WIDTH = 48
DEFAULT_EYE_HEIGHT = 64
DEFAULT_EYE_Y = 120
FACE_OFFSET_PX_PER_UNIT = 20
